# Generated by Django 6.0.6 on 2026-06-08 04:11

import clases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('codigo', models.CharField(default=clases.models.generar_codigo, max_length=6, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='clases_unidas', to=settings.AUTH_USER_MODEL)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
