# Generated by Django 6.0.6 on 2026-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='semestre',
            field=models.CharField(choices=[('1-2', 'Primer y Segundo Semestre'), ('3-4', 'Tercer y Cuarto Semestre'), ('5-6', 'Quinto y Sexto Semestre')], default='1-2', max_length=3),
        ),
    ]
