# Generated by Django 6.0.6 on 2026-06-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clase_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='semestre',
            field=models.CharField(choices=[('1-2', '1er y 2do Semestre'), ('3-4', '3er y 4to Semestre'), ('5-6', '5to y 6to Semestre')], default='1-2', max_length=3),
        ),
    ]
