# Generated by Django 6.0.6 on 2026-06-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_clase_especialidad_materia_clase_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='semestre',
            field=models.CharField(choices=[('1-2A', '1er y 2do Semestre - Grupo A'), ('1-2B', '1er y 2do Semestre - Grupo B'), ('3-4A', '3er y 4to Semestre - Grupo A'), ('3-4B', '3er y 4to Semestre - Grupo B'), ('5-6A', '5to y 6to Semestre - Grupo A'), ('5-6B', '5to y 6to Semestre - Grupo B')], default='1-2A', max_length=4),
        ),
    ]
